import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter, Roboto } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '700']
})

export const metadata = {
  title: 'Dirtysprite',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body className={roboto.className}>
      <Navbar/>
      {children}
      </body>
    </html>
  )
}
